export const LESSON_SUMMARY_TOKENS = {
  VIDEO_ANALYSIS_AGENT: 'VIDEO_ANALYSIS_AGENT',
  DOCUMENT_FORMATTING_AGENT: 'DOCUMENT_FORMATTING_AGENT',
  LAYOUT_ENGINE: 'LESSON_LAYOUT_ENGINE',
  HTML_RENDERER: 'LESSON_HTML_RENDERER',
  LESSON_SUMMARY_REPOSITORY: 'LESSON_SUMMARY_REPOSITORY',
  PROMPT_MANAGER: 'LESSON_SUMMARY_PROMPT_MANAGER',
  VALIDATION_SERVICE: 'LESSON_SUMMARY_VALIDATION_SERVICE',
  ORCHESTRATOR_SERVICE: 'LESSON_SUMMARY_ORCHESTRATOR_SERVICE',
} as const;
